import type { MockCompany } from './types'

export const MOCK_COMPANIES: MockCompany[] = [
  // ── Строительство ───────────────────────────────────────────────────────────
  {
    id: 'c-001',
    name: 'СтройГрупп',
    industry: 'Строительство',
    region: 'Москва',
    size: '100–300 сотрудников',
    description: 'Генеральный подрядчик промышленных и жилых объектов. Работают по всей России.',
    contact: { name: 'Алексей Воронов', role: 'Директор по развитию', email: 'voronov@stroygrupp.ru', phone: '+7 (495) 123-45-67' },
    signals: [
      { label: 'Открыли 8 новых вакансий', type: 'hiring' },
      { label: 'Новый объект в Подмосковье', type: 'expanding' },
    ],
    website: 'stroygrupp.ru',
    foundedYear: 2012,
  },
  {
    id: 'c-002',
    name: 'МосПроект',
    industry: 'Строительство',
    region: 'Москва',
    size: '50–150 сотрудников',
    description: 'Проектирование и строительство коммерческих помещений. Специализация — торговые центры.',
    contact: { name: 'Марина Соколова', role: 'Коммерческий директор', email: 'm.sokolova@mosprojekt.ru', phone: '+7 (495) 234-56-78' },
    signals: [
      { label: 'Быстро растут: +35% за год', type: 'growing' },
      { label: 'Получили крупный госконтракт', type: 'contract' },
    ],
    website: 'mosprojekt.ru',
    foundedYear: 2018,
  },
  {
    id: 'c-003',
    name: 'ПромСтрой',
    industry: 'Строительство',
    region: 'Екатеринбург',
    size: '200–500 сотрудников',
    description: 'Промышленное строительство и реконструкция объектов. Уральский федеральный округ.',
    contact: { name: 'Дмитрий Захаров', role: 'Генеральный директор', email: 'd.zakharov@promstroy-ural.ru', phone: '+7 (343) 345-67-89' },
    signals: [
      { label: 'Открыли новый офис в Тюмени', type: 'expanding' },
      { label: 'Нанимают прорабов и ПТО', type: 'hiring' },
    ],
    website: 'promstroy-ural.ru',
    foundedYear: 2008,
  },
  // ── Логистика ───────────────────────────────────────────────────────────────
  {
    id: 'c-004',
    name: 'ТехноТранс',
    industry: 'Логистика и транспорт',
    region: 'Екатеринбург',
    size: '50–200 сотрудников',
    description: 'Грузоперевозки по России и СНГ. Собственный парк из 80 фур.',
    contact: { name: 'Иван Петров', role: 'Директор по продажам', email: 'ivan@technotrans.ru', phone: '+7 (343) 456-78-90' },
    signals: [
      { label: 'Расширяют маршрутную сеть', type: 'expanding' },
      { label: 'Ищут корпоративных клиентов', type: 'contract' },
    ],
    website: 'technotrans.ru',
    foundedYear: 2014,
  },
  {
    id: 'c-005',
    name: 'РусЛогист',
    industry: 'Логистика и транспорт',
    region: 'Москва',
    size: '100–500 сотрудников',
    description: 'Складская и транспортная логистика. Фулфилмент для e-commerce.',
    contact: { name: 'Ольга Белова', role: 'Руководитель по партнёрствам', email: 'o.belova@ruslogist.ru', phone: '+7 (495) 567-89-01' },
    signals: [
      { label: 'Открыли склад в Подмосковье', type: 'expanding' },
      { label: 'Рост клиентской базы +50%', type: 'growing' },
    ],
    website: 'ruslogist.ru',
    foundedYear: 2016,
  },
  {
    id: 'c-006',
    name: 'УралЭкспресс',
    industry: 'Логистика и транспорт',
    region: 'Екатеринбург',
    size: '20–80 сотрудников',
    description: 'Срочная доставка грузов по Уральскому региону. Работают 24/7.',
    contact: { name: 'Сергей Кузнецов', role: 'Владелец', email: 'sk@uralexpress.ru', phone: '+7 (343) 678-90-12' },
    signals: [
      { label: 'Набирают водителей', type: 'hiring' },
      { label: 'Запускают новые направления', type: 'expanding' },
    ],
    website: 'uralexpress.ru',
    foundedYear: 2019,
  },
  // ── Юридические ─────────────────────────────────────────────────────────────
  {
    id: 'c-007',
    name: 'Правовой Центр',
    industry: 'Юридические услуги',
    region: 'Казань',
    size: '20–50 сотрудников',
    description: 'Корпоративное право, сопровождение сделок M&A, защита активов.',
    contact: { name: 'Алина Хасанова', role: 'Управляющий партнёр', email: 'a.khasanova@lawcenter-kzn.ru', phone: '+7 (843) 789-01-23' },
    signals: [
      { label: 'Открыли практику налогового права', type: 'expanding' },
      { label: 'Ищут корпоративных клиентов', type: 'contract' },
    ],
    website: 'lawcenter-kzn.ru',
    foundedYear: 2015,
  },
  {
    id: 'c-008',
    name: 'ЛексГрупп',
    industry: 'Юридические услуги',
    region: 'Москва',
    size: '30–80 сотрудников',
    description: 'Арбитраж, банкротство, взыскание дебиторской задолженности.',
    contact: { name: 'Андрей Смирнов', role: 'Партнёр', email: 'smirnov@lexgroup.ru', phone: '+7 (495) 890-12-34' },
    signals: [
      { label: 'Быстро растут: +45% за год', type: 'growing' },
      { label: 'Набирают юристов-арбитражников', type: 'hiring' },
    ],
    website: 'lexgroup.ru',
    foundedYear: 2013,
  },
  // ── IT ──────────────────────────────────────────────────────────────────────
  {
    id: 'c-009',
    name: 'СофтЛаб',
    industry: 'IT и разработка',
    region: 'Санкт-Петербург',
    size: '30–100 сотрудников',
    description: 'Аутсорс разработка веб-сервисов и корпоративного ПО. 12 лет опыта.',
    contact: { name: 'Павел Громов', role: 'CEO', email: 'gromov@softlab.ru', phone: '+7 (812) 901-23-45' },
    signals: [
      { label: 'Ищут аутсорс-партнёров', type: 'contract' },
      { label: 'Выходят на новые рынки', type: 'expanding' },
    ],
    website: 'softlab.ru',
    foundedYear: 2011,
  },
  {
    id: 'c-010',
    name: 'ДигиталКод',
    industry: 'IT и разработка',
    region: 'Казань',
    size: '20–60 сотрудников',
    description: 'Разработка мобильных приложений и интеграция с 1С. Работают с B2B.',
    contact: { name: 'Тимур Галиев', role: 'Технический директор', email: 'galiev@digitalcode.ru', phone: '+7 (843) 012-34-56' },
    signals: [
      { label: 'Нанимают мобильных разработчиков', type: 'hiring' },
      { label: 'Рост выручки +60% за год', type: 'growing' },
    ],
    website: 'digitalcode.ru',
    foundedYear: 2020,
  },
  // ── Производство ────────────────────────────────────────────────────────────
  {
    id: 'c-011',
    name: 'МеталлПром',
    industry: 'Производство',
    region: 'Екатеринбург',
    size: '100–500 сотрудников',
    description: 'Металлообработка и изготовление металлоконструкций под заказ.',
    contact: { name: 'Виктор Уваров', role: 'Директор по снабжению', email: 'uvarov@metallprom-ural.ru', phone: '+7 (343) 123-56-78' },
    signals: [
      { label: 'Обновляют производственное оборудование', type: 'expanding' },
      { label: 'Ищут поставщиков комплектующих', type: 'contract' },
    ],
    website: 'metallprom-ural.ru',
    foundedYear: 2005,
  },
  {
    id: 'c-012',
    name: 'ПластИнд',
    industry: 'Производство',
    region: 'Краснодар',
    size: '80–300 сотрудников',
    description: 'Производство пластиковых изделий и упаковки. Работают с ритейлом.',
    contact: { name: 'Наталья Орлова', role: 'Коммерческий директор', email: 'orlova@plastind.ru', phone: '+7 (861) 234-67-89' },
    signals: [
      { label: 'Запускают новую линию производства', type: 'expanding' },
      { label: 'Быстро растут: +30% за год', type: 'growing' },
    ],
    website: 'plastind.ru',
    foundedYear: 2010,
  },
  // ── Торговля ────────────────────────────────────────────────────────────────
  {
    id: 'c-013',
    name: 'ОптТорг',
    industry: 'Торговля',
    region: 'Москва',
    size: '50–200 сотрудников',
    description: 'Оптовая торговля строительными материалами. Доставка по Центральной России.',
    contact: { name: 'Роман Козлов', role: 'Руководитель закупок', email: 'kozlov@opttorg.ru', phone: '+7 (495) 345-78-90' },
    signals: [
      { label: 'Расширяют складские мощности', type: 'expanding' },
      { label: 'Ищут новых поставщиков', type: 'contract' },
    ],
    website: 'opttorg.ru',
    foundedYear: 2009,
  },
  {
    id: 'c-014',
    name: 'ДистрибМастер',
    industry: 'Торговля',
    region: 'Новосибирск',
    size: '100–300 сотрудников',
    description: 'FMCG-дистрибуция в Сибирском регионе. 5 000+ торговых точек в базе.',
    contact: { name: 'Екатерина Полякова', role: 'Директор по продажам', email: 'polyakova@distrib-master.ru', phone: '+7 (383) 456-89-01' },
    signals: [
      { label: 'Открыли новый распред. центр', type: 'expanding' },
      { label: 'Выручка выросла на 40%', type: 'growing' },
    ],
    website: 'distrib-master.ru',
    foundedYear: 2007,
  },
  // ── Медицина ────────────────────────────────────────────────────────────────
  {
    id: 'c-015',
    name: 'МедКлиника Плюс',
    industry: 'Медицина',
    region: 'Санкт-Петербург',
    size: '30–100 сотрудников',
    description: 'Частная многопрофильная клиника. Корпоративное медобслуживание компаний.',
    contact: { name: 'Лариса Соловьёва', role: 'Главный врач', email: 'soloveva@medclinika.ru', phone: '+7 (812) 567-90-12' },
    signals: [
      { label: 'Открывают второй филиал', type: 'expanding' },
      { label: 'Ищут корпоративных клиентов', type: 'contract' },
    ],
    website: 'medclinika.ru',
    foundedYear: 2017,
  },
  {
    id: 'c-016',
    name: 'СтомаПро',
    industry: 'Медицина',
    region: 'Казань',
    size: '20–50 сотрудников',
    description: 'Сеть стоматологических клиник. 3 филиала в Казани и области.',
    contact: { name: 'Рустам Ахметов', role: 'Управляющий директор', email: 'akhmetov@stomapro.ru', phone: '+7 (843) 678-01-23' },
    signals: [
      { label: 'Открывают новый кабинет', type: 'expanding' },
      { label: 'Нанимают администраторов', type: 'hiring' },
    ],
    website: 'stomapro.ru',
    foundedYear: 2016,
  },
  // ── Консалтинг / Маркетинг ──────────────────────────────────────────────────
  {
    id: 'c-017',
    name: 'БизнесКонсалт',
    industry: 'Консалтинг',
    region: 'Москва',
    size: '20–60 сотрудников',
    description: 'Управленческий консалтинг для среднего бизнеса. Стратегия и операционная эффективность.',
    contact: { name: 'Михаил Лебедев', role: 'Партнёр', email: 'lebedev@bizconsult.ru', phone: '+7 (495) 789-12-34' },
    signals: [
      { label: 'Запустили новую практику', type: 'expanding' },
      { label: 'Рост клиентской базы +55%', type: 'growing' },
    ],
    website: 'bizconsult.ru',
    foundedYear: 2014,
  },
  {
    id: 'c-018',
    name: 'МаркетПро',
    industry: 'Маркетинг и реклама',
    region: 'Краснодар',
    size: '15–40 сотрудников',
    description: 'Performance-маркетинг и SEO для B2B-компаний. Работают по всей России.',
    contact: { name: 'Анастасия Иванова', role: 'CEO', email: 'ivanova@marketpro.ru', phone: '+7 (861) 890-23-45' },
    signals: [
      { label: 'Нанимают специалистов по контексту', type: 'hiring' },
      { label: 'Быстро растут: +70% за год', type: 'growing' },
    ],
    website: 'marketpro.ru',
    foundedYear: 2021,
  },
]
